### ISSUE TITLE
The sponsorship info button wrongly placed

### ISSUE THREAD

**Issue by anshulwadhawan** [fossasia/events.fossasia.org#14]
Current State: On viewing the website in Redmi Note 3,the sponsorship info button seems to be wrongly placed.
Expected State: The button should be at some gap from the image below.
![screenshot_2017-10-04-19-29-28-947_com android chrome](https://user-images.githubusercontent.com/25061477/31215702-35b9cf08-a9ce-11e7-897f-598e067439b5.png)
I wish to work on this issue.

**Comment by Tshiteej-zz** [comment]
Added a commit by rectifying the error
