### ISSUE TITLE
Excessive gap between images

### ISSUE THREAD

**Issue by anshulwadhawan** [fossasia/events.fossasia.org#15]
Current State: On viewing the website in Redmi Note 3,there is excessive gap between images of the sponsorship section.
Expected State: A marginal gap of 10-20 pixels should be given.

![screenshot_2017-10-04-19-29-33-474_com android chrome](https://user-images.githubusercontent.com/25061477/31215836-c4f0a804-a9ce-11e7-80ec-5982a28e2411.png)
I want to work on this issue.

**Comment by pandyamarut** [comment]
Issue is still unsolved? 
then please do inform. 
have to go through large code base then have to check for the issue.
