### ISSUE TITLE
Add section for Science Hack Days

### ISSUE THREAD

**Issue by mariobehling** [fossasia/events.fossasia.org#2]
Currently there is no section for science hack days and a link to sciencehack.asia

**Comment by Achint08** [comment]
Hello @mariobehling  I would like to work on this. Can you assign me this work?Please provide me with some details about what to include in the section?

**Comment by raw-at** [comment]
Hey @mariobehling i can solve this issue just give the hint about the layout and if any backend work related to nodejs or mongo is required let me know its my first time to open source contribution so please help me to be in Open source community.

**Comment by mariobehling** [comment]
@raw-at Thanks. It is not an urgent task and I will take care of it, when I have time rather than providing a long explanation here. Cheers.
