### ISSUE TITLE
Text color needs to be fixed on hover.

### ISSUE THREAD

**Issue by abhieshekumar** [fossasia/events.fossasia.org#20]
**Steps to replicate issue -**

1. Visit  [Fossaia Events Page](https://events.fossasia.org/)
2. Scroll down to _2017_ (Image 1)
3. Hovering on _Sponsor FOSSASIA_ makes the color of text and background same (Image 2)

**Image 1**
![Image 1](https://user-images.githubusercontent.com/24494390/45830738-5ef9dc80-bd1b-11e8-80dc-75f1afe2e486.png)

**Image 2**
![Image 2](https://user-images.githubusercontent.com/24494390/45830781-76d16080-bd1b-11e8-8d7f-a63b513e22cb.png)

I will like to take take up this issue.

**Comment by Ridvmodi** [comment]
I will like to work on this issue, can I?

**Comment by mariobehling** [comment]
Please go ahead.

**Comment by Ridvmodi** [comment]
Ok, sir, I am working on it.

**Comment by abhieshekumar** [comment]
@mariobehling Sir after I raised the issue, I have already tried to fix the issue and submitted a pull request https://github.com/fossasia/events.fossasia.org/pull/21 for it. Please take a look.
@Ridvmodi
