### ISSUE TITLE
Some padding must be given before copyright symbol ,but now it is completely aligned with the border.

### ISSUE THREAD

**Issue by Ridvmodi** [fossasia/events.fossasia.org#22]
![issue 3](https://user-images.githubusercontent.com/38110540/45926240-29810900-bf3e-11e8-849f-344c41643b64.png)

**Comment by amrs-tech** [comment]
Let me try to fix this issue.

**Comment by Ridvmodi** [comment]
Fixed sir, please check pull request #26  @mariobehling @hongquan @hongquan 
Now it look like's that

**Comment by Ridvmodi** [comment]
![screenshot 255](https://user-images.githubusercontent.com/38110540/47260091-40316600-d4d2-11e8-9a4a-9a182fc0ea7a.png)

**Comment by mariobehling** [comment]
Closing this in favor of https://github.com/fossasia/events.fossasia.org/issues/27
