### ISSUE TITLE
Number of errors in console

### ISSUE THREAD

**Issue by isuruAb** [fossasia/events.fossasia.org#5]
<img width="1272" alt="screen shot 2017-09-08 at 7 26 37 pm" src="https://user-images.githubusercontent.com/7692626/30214920-c955b190-94cb-11e7-92d9-5d1b6db046e8.png">

**Comment by championshuttler** [comment]
@isuruAb can i work on the issue?
thank you

**Comment by isuruAb** [comment]
@championshuttler  yes sure
