### ISSUE TITLE
Fix font colour of contact number in footer

### ISSUE THREAD

**Issue by dilpreetsio** [fossasia/events.fossasia.org#6]
![screenshot from 2017-09-08 22-49-25](https://user-images.githubusercontent.com/12807846/30223348-20323dd2-94e8-11e7-8827-7ef6bb60c57b.png)

**Comment by mittalprince** [comment]
sir may i work on this issue @geekyd

**Comment by dilpreetsio** [comment]
@mittalprince 
Sure go ahead!

**Comment by mittalprince** [comment]
sir i'm new in this field so please may you guide me what steps should i follow to solve this issue.

**Comment by Rishabh-Kumar-Bothra** [comment]
@mittalprince have you started working on the issue?

**Comment by mittalprince** [comment]
yes sir and i find the solution also.

**Comment by mittalprince** [comment]
sir but there are many mistakes in code like same id has been given twice and extra semicolon is also used etc. what will i do sir now

**Comment by Rishabh-Kumar-Bothra** [comment]
open a issue if you find any error and PR if you have solved the issue.
no need of using sir.
thank you

**Comment by dilpreetsio** [comment]
@mittalprince Please open a separate issue for it.

**Comment by mittalprince** [comment]
@geekyd  sir how to make PR

**Comment by dilpreetsio** [comment]
@mittalprince Please follow this https://guides.github.com/activities/hello-world/#pr

**Comment by mittalprince** [comment]
thanks sir 
i will see it

**Comment by mittalprince** [comment]
sir i make PR please review it .
And please guide me if i made a wrong PR
thanks

**Comment by nanspro** [comment]
issue has been fixed you can close it now

**Comment by dilpreetsio** [comment]
Closing this via #12
